spring:
  application:
    name: kiire-back-archetype
  webflux:
    base-path: /archetype

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kiire
    username: postgres
    password: K11r3
  data:
    r2dbc:
      repositories:
        enabled: true

logging:
  level:
    co.com.kiire: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

server:
  port: 9079