spring:
  application:
    name: jineteapp-back


  r2dbc:
    url: r2dbc:postgresql://localhost:5432/jineteapp
    username: santiago
    password: 0406
  data:
    r2dbc:
      repositories:
        enabled: true

logging:
  level:
    co.com.jineteapp: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

server:
  port: 8080