spring:
  application:
    name: archetype-back-api
  webflux:
    base-path: /archetype

  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  data:
    r2dbc:
      repositories:
        enabled: true

logging:
  level:
    co.com.kiire: DEBUG

server:
  port: 8080